### ISSUE TITLE
JuliaMicroscopy?

### ISSUE THREAD

**Issue by mkitti** [JuliaImages/MultiChannelColors.jl#1]
Perhaps this would be a good fit for https://github.com/JuliaMicroscopy ?

**Comment by timholy** [comment]
Definitely worth considering, but let's determine the resolution of #2 first. If this generalizes to hyperspectral imaging then it would be useful for, e.g., geospatial imaging and that doesn't naturally fit in JuliaMicroscopy.

**Comment by timholy** [comment]
With the rename to MultiChannelColors and examples that use Landsat imaging in the docs, I don't think moving to JuliaMicroscopy makes as much sense as it did when the package focus was narrower.
